---
name: Dependencies 

runs:
  using: 'composite'
  steps: 
    - name: Install package dependencies 📄
      run: |
        pak::local_install_deps(".", upgrade=FALSE, ask=FALSE)
      shell: Rscript {0}


