---
name: Check 📦

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: check-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-test:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Checkout Repo Templates      
        uses: actions/checkout@v4
        with:
          ref: main
          repository: boehringer-ingelheim/dv.templates
          path: templates
  
      - name: Install package dependencies 📄
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main

      - name: Single Build 📦        
        run: Rscript templates/pkg_pipeline/single_build.R

      - name: Build site 🔧
        run: pkgdown::build_site()
        shell: Rscript {0}
  
      - name: Check URLs 🌐
        run: |
          lychee . --format markdown --verbose --no-progress >> $GITHUB_STEP_SUMMARY
        shell: bash  

      - name: Checkout gh-pages branch ⬇️        
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - name: Deploy to GitHub pages 📰        
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: gh-pages
          folder: docs


