---
name: Pkgdown 📖

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: pkgdown-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pkgdown:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    permissions:
      contents: write

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Build site 🔧
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Checkout gh-pages branch ⬇️
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - name: Deploy to GitHub pages 📰
        if: (github.event_name == 'push') && (github.ref_name == 'main')
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: gh-pages
          folder: docs
          clean-exclude: |
            .github/*
