---
name: Styler 🦄

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: styler-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  styler:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Install package dependencies 📄
        uses: zsigmas/dv.templates/.github/actions/dependencies@include_qc_separate_steps     

      - name: Run styler 🦄
        run: |
            changes <- styler::style_pkg(dry = "on")
            if (sum(changes[["changed"]]) > 0) {
              stop(
                "Styler has detected styling issues. Please run styler::style_pkg() and re-commit your changes."
              )
            }
        shell: Rscript {0}

