---
name: Styler 🦄

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: styler-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  styler:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Install package dependencies 📄
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main

      - name: Run styler 🦄
        run: |
            changes <- styler::style_pkg(dry="on")
            sum(changes[["changed"]])
        shell: Rscript {0}

