---
name: Test and QC 🧪

on:  
  workflow_call:

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Checkout Repo Templates ⬇️  
        uses: actions/checkout@v4
        with:
          ref: main
          repository: boehringer-ingelheim/dv.templates
          path: templates

      - name: Install package dependencies 📄
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main     

      - name: Test and QC 🧪
        run: Rscript templates/scripts/test.R

      - name: Archive validation results ⬆️
        uses: actions/upload-artifact@v4
        with:
          name: val_results
          path: inst/validation/results