---
name: Test and QC 🧪

on:  
  workflow_call:

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEMPLATE_REF: main
  TEMPLATE_REPO: boehringer-ingelheim/dv.templates

jobs:
  test:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    steps:
      - name: Checkout project ⬇️
        uses: actions/checkout@v4

      - name: Checkout templates repo ⬇️  
        uses: actions/checkout@v4
        with:
          ref: ${{env.TEMPLATE_REF}}
          repository: ${{env.TEMPLATE_REPO}}
          sparse-checkout: |
            scripts/
            inst/validation
          path: templates

      - name: Overwrite quality control scripts with dv.templates ones 🧹
        run: |
          # Paths to the directories
          TEMPLATE_DIR="templates/inst/validation"
          REPO_DIR="inst/validation"
          
          # Run the diff command and capture the output
          DIFF_OUTPUT=$(diff -qr "$TEMPLATE_DIR" "$REPO_DIR")

          echo "# Quality control files" | tee -a $GITHUB_STEP_SUMMARY
          
          # Check if the diff command found any differences
          if [ -n "$DIFF_OUTPUT" ]; then
            echo "Warning: The contents of the directories are different!" | tee -a $GITHUB_STEP_SUMMARY
            echo "Modified files:" | tee -a $GITHUB_STEP_SUMMARY
            echo "$DIFF_OUTPUT" | tee -a $GITHUB_STEP_SUMMARY
          else
            echo "The directories are identical." | tee -a $GITHUB_STEP_SUMMARY
          fi

          # Always overwrite

          rm -rf "$REPO_DIR"/*

          # Move contents of REPO_DIR to TEMPLATE_DIR
          mv "$TEMPLATE_DIR"/* "$REPO_DIR"

      - name: Install package dependencies 📄
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main     

      - name: Test and QC 🧪        
        run: Rscript templates/scripts/test_qc_pkg.R

      - name: Archive validation results ⬆️
        uses: actions/upload-artifact@v4
        with:
          name: val_results
          path: inst/validation/results